/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _mulle_atinit_include_h__
#define _mulle_atinit_include_h__

// remove with `mulle-sourcetree mark mulle-thread no-header`
// rename with `mulle-sourcetree mark mulle-thread set include whatever.h`
# include <mulle-thread/mulle-thread.h>   // mulle-thread

// remove with `mulle-sourcetree mark mulle-dlfcn no-header`
// rename with `mulle-sourcetree mark mulle-dlfcn set include whatever.h`
# include <mulle-dlfcn/mulle-dlfcn.h>   // mulle-dlfcn

#endif
